const tutorialData = [
  {
    id: 1,
    title: "Teknik Analiz Eğitimi (online)",
    img: "https://images.unsplash.com/photo-1509701852059-c221a6f1e878?q=80&w=3191&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    features: [
      "Ömür boyu whatsapp desteği",
      "20+ saat eğitim",
      "10+ yıl deneyimli eğitmen",
      "Tekrarlar/Ödevler",
      "Strateji dersleri",
      "Eğitim dökümanlarına sınırsız erişim",
      "Soru cevap",
      "Pratik dersler",
      "Web sitemizde panel",
      "Borsa bilgisi gerektirmez",
    ],
    fakePrice: 14.999,
    price: 9999,
    description:
      " Borsa dünyasına merakla bakıyor ama nereden başlayacağınızı bilemiyormusunuz? Temel Borsa Eğitimi tam size göre! Bu eğitim,yatırım yapmanın temellerini öğrenmek isteyen yeni başlayanlar için özenle hazırlanmıştır. Borsa kavramlarından hisse senetlerinin mantığına, piyasa dinamiklerinden alım-satım süreçlerine kadar her detayı en sade ve anlaşılır şekilde öğreneceksiniz. Bu eğitimle finansal özgürlüğünüzün ilk adımını atarken, piyasanın karmaşık görünen yüzünü bir rehber eşliğinde keşfedin. Artık borsa sizin için bir muamma değil; fırsatlarla dolu bir dünya olacak!",
    detailFeatures: [
      "Teknik analiz eğitimi",
      "Tradingview ve matriks kullanımı",
      "Ağırlıklı ortalamalar",
      "İndikatorler ",
      "Destek-Direnç",
      "Ayı-Boğa piyasası",
      "Stop loss detayları",
      "Trend çizimi",
      "Püf noktalar ",
      "Bar takip",
      "Formasyonlar ",
      "Uyumsuzluklar ",
      "Bedelli-Bedelsiz",
      "Temettü-Bölünme-Birleşme",
      "Emir tipleri",
      "Devre kesici",
      "Varant-Viop",
      "Radar",
      "Mevsimsellik Analizi",
      "Endeksler",
      "Bilançolar",
      "Portfoy yöneticiliği",
    ],
  },
  {
    id: 2,

    title: "Teknik Analiz Eğitimi (Yüz yüze)",
    img: "https://images.unsplash.com/photo-1655337690631-7f8a566bb60c?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    features: [
      "Ömür boyu whatsapp desteği",
      "20+ saat eğitim",
      "10+ yıl deneyimli eğitmen",
      "Tekrarlar/Ödevler",
      "Strateji dersleri",
      "Eğitim dökümanlarına sınırsız erişim",
      "Soru cevap",
      "Pratik dersler",
      "Web sitemizde panel",
      "Borsa bilgisi gerektirmez",
    ],
    fakePrice: 24.999,
    price: 19.999,
    description:
      " Borsa dünyasına merakla bakıyor ama nereden başlayacağınızı bilemiyormusunuz? Temel Borsa Eğitimi tam size göre! Bu eğitim,yatırım yapmanın temellerini öğrenmek isteyen yeni başlayanlar içinözenle hazırlanmıştır. Borsa kavramlarından hisse senetlerinin mantığına,piyasa dinamiklerinden alım-satım süreçlerine kadar herdetayı ensade ve anlaşılır şekilde öğreneceksiniz. Bu eğitimle finansal özgürlüğünüzün ilk adımını atarken, piyasanın karmaşıkgörünen yüzünü bir rehber eşliğinde keşfedin. Artık borsa sizin içinbir muamma değil; fırsatlarla dolu bir dünya olacak!",
    detailFeatures: [
      "Teknik analiz eğitimi",
      "Tradingview ve matriks kullanımı",
      "Ağırlıklı ortalamalar",
      "İndikatorler ",
      "Destek-Direnç",
      "Ayı-Boğa piyasası",
      "Stop loss detayları",
      "Trend çizimi",
      "Püf noktalar ",
      "Bar takip",
      "Formasyonlar ",
      "Uyumsuzluklar ",
      "Bedelli-Bedelsiz",
      "Temettü-Bölünme-Birleşme",
      "Emir tipleri",
      "Devre kesici",
      "Varant-Viop",
      "Radar",
      "Mevsimsellik Analizi",
      "Endeksler",
      "Bilançolar",
      "Portfoy yöneticiliği",
    ],
  },
  {
    id: 3,

    title: "Temel Analiz Eğitimi (Online)",
    img: "https://images.unsplash.com/photo-1509701852059-c221a6f1e878?q=80&w=3191&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    features: [
      "Ömür boyu whatsapp desteği",
      "20+ saat eğitim",
      "10+ yıl deneyimli eğitmen",
      "Tekrarlar/Ödevler",
      "Strateji dersleri",
      "Eğitim dökümanlarına sınırsız erişim",
      "Soru cevap",
      "Pratik dersler",
    ],
    fakePrice: 14.999,
    price: 9999,
    description:
      " Borsa dünyasına merakla bakıyor ama nereden başlayacağınızı bilemiyormusunuz? Temel Borsa Eğitimi tam size göre! Bu eğitim,yatırım yapmanın temellerini öğrenmek isteyen yeni başlayanlar içinözenle hazırlanmıştır. Borsa kavramlarından hisse senetlerinin mantığına,piyasa dinamiklerinden alım-satım süreçlerine kadar herdetayı ensade ve anlaşılır şekilde öğreneceksiniz. Bu eğitimle finansal özgürlüğünüzün ilk adımını atarken, piyasanın karmaşıkgörünen yüzünü bir rehber eşliğinde keşfedin. Artık borsa sizin içinbir muamma değil; fırsatlarla dolu bir dünya olacak!",
    detailFeatures: [
      "Bilanço okumak",
      "Bilanço analiz etmek",
      "Gelir tablosu analiz etmek",
      "Gelir tablosu okumak",
      "Aktif-Pasif detaylı anlatım",
      "Strateji geliştirme dersleri",
      "Aktif whatsapp grubu üyeliği",
    ],
  },
  {
    id: 4,

    title: "Temel Analiz Eğitimi (Yüz yüze)",
    img: "https://images.unsplash.com/photo-1655337690631-7f8a566bb60c?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    features: [
      "Ömür boyu whatsapp desteği",
      "20+ saat eğitim",
      "10+ yıl deneyimli eğitmen",
      "Tekrarlar/Ödevler",
      "Strateji dersleri",
      "Eğitim dökümanlarına sınırsız erişim",
      "Soru cevap",
      "Pratik dersler",
    ],
    fakePrice: 24.999,
    price: 19.999,
    description:
      " Borsa dünyasına merakla bakıyor ama nereden başlayacağınızı bilemiyormusunuz? Temel Borsa Eğitimi tam size göre! Bu eğitim,yatırım yapmanın temellerini öğrenmek isteyen yeni başlayanlar içinözenle hazırlanmıştır. Borsa kavramlarından hisse senetlerinin mantığına,piyasa dinamiklerinden alım-satım süreçlerine kadar herdetayı ensade ve anlaşılır şekilde öğreneceksiniz. Bu eğitimle finansal özgürlüğünüzün ilk adımını atarken, piyasanın karmaşıkgörünen yüzünü bir rehber eşliğinde keşfedin. Artık borsa sizin içinbir muamma değil; fırsatlarla dolu bir dünya olacak!",
    detailFeatures: [
      "Bilanço okumak",
      "Bilanço analiz etmek",
      "Gelir tablosu analiz etmek",
      "Gelir tablosu okumak",
      "Aktif-Pasif detaylı anlatım",
      "Strateji geliştirme dersleri",
      "Aktif whatsapp grubu üyeliği",
    ],
  },
];

export default tutorialData;
